### PR TITLE
Multiple Changes

### PR DESCRIPTION
**Pull request by XavierGuertin**
**Quotation:**
- Make sure that the quotation page is only accessible by customers

**Tracking Order:**
- Increased size of images
- Changed all images for PNGs so we don't have white backgrounds

**UpdateOrderStatus:**
- default status changed to courier-assigned (was null and causing error)
- if new status then updates the order's courierUID & courierName values
- Fixed the username not showing up by addind customerUsername to the DB when creating a user

**User Portal:**
- CourierName assigned to the order is displayed if not null

**Database:**
- Orders table:
  - courierUID added
  - courierName added
  - customerUsername added
- Users table:
  - added username

**Navbar:**
- add username to localStorage, if not yet defined value displayed is "Portal"

TrackingOrder
Screenshot_3

### CODE REVIEW

**Comment by Fetyali7** [comment]
I literally wanted to make some changes (kind of the same changes) to my part today.

**Review by Fetyali7 — COMMENTED** [review]
Looks good!

**Review by Fetyali7 — APPROVED** [review]

**Review by lo-vil — APPROVED** [review]
Looking good bruva

**Review by GetGabed — APPROVED** [review]
oi noice gud

**Pull request merged**
